services:

  gateway_service:
    build:
      context: .
      dockerfile: ./gateway_service/Dockerfile
    image: gateway_service:latest
    container_name: gs

    networks:
     - app-network

  account_service:
    build:
      context: .
      dockerfile: ./account_service/Dockerfile
    image: account_service:latest
    container_name: as
  
    networks:
     - app-network
  
  postgres_db:
    image: postgres:17-alpine
    container_name: db

    env_file:
      - .env.db

    volumes:
     - postgres-data:/var/lib/postgresql/data

    networks:
     - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: