services:

  gateway_service:
    build:
      context: .
      dockerfile: ./gateway_service/Dockerfile
    image: gateway_service:latest
    container_name: gateway_service

    networks:
     - app-network

  account_service:
    build:
      context: .
      dockerfile: ./account_service/Dockerfile
    image: account_service:latest
    container_name: account_service

    env_file:
      - .env.db

    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
     - app-network
  
  admin_service:
    build:
      context: .
      dockerfile: ./admin_service/Dockerfile
    image: admin_service:latest
    container_name: admin_service

    env_file:
      - .env.db 

    depends_on:
      postgres_db:
        condition: service_healthy

    networks:
     - app-network

  order_service:
    build:
      context: .
      dockerfile: ./order_service/Dockerfile
    image: order_service:latest
    container_name: order_service

    env_file:
      - .env.db
    
    depends_on:
      postgres_db:
        condition: service_healthy

    networks:
      - app-network
  
  postgres_db:
    image: postgres:17-alpine
    container_name: db

    env_file:
      - .env.db

    volumes:
     - postgres-data:/var/lib/postgresql/data

    networks:
     - app-network

    healthcheck:                                    
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
#ОТЛАДКА БАЗЫ ДАННЫХ
  adminer:
    image: adminer
    container_name: adminer

    ports:
    - "8080:8080"

    networks:
    - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: